name: Deploy Frontend to ECS

on:
  push:
    branches:
      - main  # O la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Región de tu preferencia

      # Crear imagen Docker y subirla a ECR
      - name: Build and Push Docker image to ECR
        run: |
          # Login a ECR
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 362079385999.dkr.ecr.us-east-1.amazonaws.com
          
          # Construir la imagen Docker
          docker build -t frontend-fondos .
          
          # Etiquetar y subir al repositorio
          docker tag frontend-fondos:latest 362079385999.dkr.ecr.us-east-1.amazonaws.com/frontend-fondos:latest
          docker push 362079385999.dkr.ecr.us-east-1.amazonaws.com/frontend-fondos:latest

      # Actualizar ECS con la nueva imagen
      - name: Update ECS service
        run: |
          # Actualizar servicio ECS
          aws ecs update-service \
            --cluster Infra-ECS-Cluster-FondosApp-Frontend-Cluster-40f15e7c \
            --service frontend-fondos-service \
            --force-new-deployment
